export enum Technologies {
  'Azure' = 'azure',
  'CSS' = 'css',
  'Docker' = 'docker',
  'Express' = 'express',
  'GIT' = 'git',
  'HTML' = 'html',
  'JavaScript' = 'javascript',
  'Laravel' = 'laravel',
  'MongoDB' = 'mongodb',
  'MySQL' = 'mysql',
  'NextJS' = 'nextjs',
  'NodeJS' = 'nodejs',
  'PHP' = 'php',
  'React' = 'react',
  'Supabase' = 'supabase',
  'TypeScript' = 'typescript',
}
